import "./globals.css";
import React from "react";
import Header from "@/components/main/header/header";
import Providers from "@/components/store/provider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body className="font-escore">
                <Providers>
                    <Header />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
