import "./globals.css";
import React from "react";
import Header from "@/components/main/header/header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body className="font-escore">
                <Header />
                {children}
            </body>
        </html>
    );
}
